<div style="text-align:center; font-family:Arial; padding:10px;">

  <div style="padding:20px;">
    <h2 style="margin:0;">Mathematics & Statistics for AI and Data Engineering using Python</h2>
  </div>

  <div style="margin-top:15px;">
    <h3 style="margin:5px 0;">Md. Arifur Rahman Sarkar</h3>
    <p style="margin:2.5px; text-align:center; ">Software Engineer (.NET), ASA Bangladesh</p>
    <p style="margin:2.5px; text-align:center; ">B.Sc. (ICT), PMAIDE (CSE, DU)</p>
  </div>

</div>


In [2]:
import numpy as np

matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])
Addition = matrix_A + matrix_B

print(Addition)

[[ 6  8]
 [10 12]]


In [3]:
import numpy as np

matrix_C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_D = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
Addition = matrix_C + matrix_D

print(Addition)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [5]:
import numpy as np

matrix_E = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_F = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
Product = np.dot(matrix_E, matrix_F)

print(Product)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [7]:
import numpy as np

matrix_G = np.array([[1, 2, 9], [4, 5, 6], [7, 8, 3]])
Inverse = np.linalg.inv(matrix_G)

print(Inverse)

[[ 3.09622474e+15 -6.19244949e+15  3.09622474e+15]
 [-2.81474977e+15  5.62949953e+15 -2.81474977e+15]
 [ 2.81474977e+14 -5.62949953e+14  2.81474977e+14]]


In [8]:
import numpy as np

matrix_H = np.array([[1, 2, 9], [4, 5, 6], [7, 8, 3]])
Transpose = matrix_H.T

print(Transpose)

[[1 4 7]
 [2 5 8]
 [9 6 3]]
